#!/usr/bin/env python
"""Load the term.

Students, courses and enrollments come from `../seed/` — the same JSON the
registrar console is seeded from, generated by `node gen_seed.js` in the repo
root. One fictional school, one roster, two halves of the project that agree
with each other.

Gradebook, attendance and support plans are generated here, deterministically,
and shaped so the watchlist has real cases on it: cohort-wide gaps on specific
skills, students whose problem is submission rather than comprehension, students
sliding across several subjects at once, and students excelling in one department
while struggling in another.

    python seed.py            # rebuild halverson.db from scratch
    python seed.py --keep     # add only what is missing
"""
from __future__ import annotations

import argparse
import json
import random
import statistics
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from app.catalog import COHORT_GAP as CATALOG_GAP                       # noqa: E402
from app.catalog import SKILLS as CATALOG_SKILLS, catalog_fields       # noqa: E402
from app.config import get_settings                                    # noqa: E402
from app.finance_seed import seed_finance                              # noqa: E402
from app.db import Base, SessionLocal, engine                          # noqa: E402
from app.models import (Assessment, AttendanceDay, Course, Enrollment,  # noqa: E402
                        Intervention, InventoryItem, Score, Student)

settings = get_settings()
TODAY = settings.today
TERM_START = date(2026, 8, 10)          # week 1, Monday
SEED_DIR = Path(__file__).parent.parent / "seed"
RNG = random.Random(20260912)

# Four strands per course, and the one the whole cohort finds hard — both from
# the course of study mapping in app/catalog.py.
SKILLS = CATALOG_SKILLS
COHORT_GAP = CATALOG_GAP
KINDS = [("homework", 20, 0.5), ("quiz", 25, 1.0), ("lab", 40, 1.2),
         ("project", 60, 1.6), ("test", 100, 2.0)]

# base mastery, points drifted per week, missing-work rate, absence rate
ARCHETYPES: dict[str, tuple[float, float, float, float]] = {
    "excelling":    (97.0,  0.5, 0.01, 0.02),
    "rising":       (89.0,  2.4, 0.02, 0.03),
    "steady":       (88.5,  0.0, 0.02, 0.03),
    "slipping":     (91.0, -3.2, 0.05, 0.04),
    "low":          (76.0, -0.4, 0.08, 0.05),
    "missing-work": (90.0, -0.6, 0.30, 0.06),
    "attendance":   (85.0, -1.3, 0.14, 0.20),
}
# A plausible school, not a school of crises: most students are fine, and the
# support office has a list it can actually work through in a week.
MIX = (["excelling"] * 8 + ["rising"] * 5 + ["steady"] * 30 + ["slipping"] * 4
       + ["low"] * 5 + ["missing-work"] * 4 + ["attendance"] * 4)


def school_days(start: date, end: date) -> list[date]:
    out, d = [], start
    while d <= end:
        if d.weekday() < 5:
            out.append(d)
        d += timedelta(days=1)
    return out


def load_console_seed() -> tuple[list[dict], list[dict], list[dict]]:
    if not SEED_DIR.exists():
        sys.exit(f"No {SEED_DIR} — run `node gen_seed.js` in the repo root first.")
    students = json.loads((SEED_DIR / "catalog__students.json").read_text())["list"]
    courses = [json.loads(p.read_text()) for p in sorted(SEED_DIR.glob("courses__*.json"))]
    inventory = [json.loads(p.read_text()) for p in sorted(SEED_DIR.glob("inventory__*.json"))]
    if not students or not courses:
        sys.exit(f"{SEED_DIR} is missing students or courses — re-run `node gen_seed.js`.")
    return students, courses, inventory


def build(keep: bool = False) -> None:
    if not keep:
        Base.metadata.drop_all(bind=engine)
    Base.metadata.create_all(bind=engine)
    raw_students, raw_courses, raw_inventory = load_console_seed()
    db = SessionLocal()
    try:
        if keep and db.query(Student).count():
            print("Records already present; --keep leaves them alone.")
            return

        # --- students ---------------------------------------------------
        students: dict[str, Student] = {}
        for row in raw_students:
            surname = row["name"].split()[-1]
            st = Student(
                sid=row["sid"], name=row["name"], grade=row["grade"], homeroom=row["homeroom"],
                guardian_name=f"{RNG.choice('ADEJKLMNRST')}. {surname}",
                guardian_email=f"{surname.lower()}.family@example.edu",
            )
            db.add(st)
            students[st.sid] = st
        db.flush()

        order = sorted(students.values(), key=lambda s: s.sid)
        archetype = {s.sid: MIX[i % len(MIX)] for i, s in enumerate(order)}
        # Per-student affinity per strand: why two students in one class have
        # different weak spots rather than all sagging on the same one.
        affinity = {s.sid: {} for s in order}

        # --- courses and enrollments ------------------------------------
        courses: dict[str, Course] = {}
        for row in raw_courses:
            c = Course(**({"title": row["title"], "dept": row["dept"]} | catalog_fields(row["code"])),
                       code=row["code"], teacher=row["teacher"], period=row.get("period") or 0,
                       room=row.get("room") or "TBD", capacity=row["capacity"],
                       signups=[int(n or 0) for n in row.get("signups") or []],
                       term=row.get("term") or settings.term)
            db.add(c)
            courses[c.code] = c
        db.flush()

        for row in raw_courses:
            c = courses[row["code"]]
            for entry in row.get("roster", []):
                st = students.get(entry["sid"])
                if st is None:
                    continue
                db.add(Enrollment(student_id=st.id, course_id=c.id,
                                  status=entry.get("state", "enrolled")))
        db.flush()

        # --- stockroom (same items the registrar console shows) -----------
        for row in raw_inventory:
            db.add(InventoryItem(
                sku=row["sku"], name=row["name"], category=row["category"], unit=row.get("unit", "unit"),
                on_hand=int(row.get("onHand", 0)), reorder_point=int(row.get("reorderPoint", 0)),
                par=max(1, int(row.get("par", 1))), location=row.get("location", "Main supply room"),
                supplier=row.get("supplier", "Central District Warehouse"),
                unit_cost=float(row.get("unitCost", 0.0)),
                last_counted=date.fromisoformat(row["lastCounted"]) if row.get("lastCounted") else None,
                linked_courses=list(row.get("linkedCourses") or []),
                requisitioned=bool(row.get("requisitioned", False))))
        db.flush()

        # --- gradebook ---------------------------------------------------
        days = school_days(TERM_START, TODAY)
        weeks = [days[i:i + 5] for i in range(0, len(days), 5)]
        n_assess = 0
        n_scores = 0

        for code, course in courses.items():
            skills = SKILLS.get(code) or ["core skills", "practice", "application", "review"]
            gap_skill = COHORT_GAP.get(code)
            course_offset = RNG.uniform(-2.5, 2.5)

            plan: list[tuple[str, str, int, int]] = []   # skill, kind, week index, seq
            for i, skill in enumerate(skills):
                for j in range(2):
                    plan.append((skill, KINDS[(i + j) % len(KINDS)][0], min(i + j * 2, len(weeks) - 1), j))
            plan.append((skills[-1], "test", len(weeks) - 1, 9))
            # Two pieces not yet due, to exercise the "graded so far" boundary.
            upcoming = [(skills[0], "homework"), (skills[1], "quiz")]

            assessments: list[Assessment] = []
            for idx, (skill, kind, wk, _seq) in enumerate(plan):
                mx, weight = next((m, w) for k, m, w in KINDS if k == kind)
                week_days = weeks[min(wk, len(weeks) - 1)]
                due = week_days[min(2 + idx % 3, len(week_days) - 1)]
                a = Assessment(
                    course_id=course.id,
                    title=f"{skill.title()} {kind}" if kind != "test" else f"Unit test — {skill}",
                    kind=kind, skill=skill, max_points=float(mx), weight=weight,
                    assigned_on=due - timedelta(days=5), due_on=due)
                db.add(a)
                assessments.append(a)
            for k, (skill, kind) in enumerate(upcoming):
                mx, weight = next((m, w) for kk, m, w in KINDS if kk == kind)
                due = TODAY + timedelta(days=3 + 2 * k)
                db.add(Assessment(course_id=course.id, title=f"{skill.title()} {kind}",
                                  kind=kind, skill=skill, max_points=float(mx), weight=weight,
                                  assigned_on=TODAY - timedelta(days=1), due_on=due))
            db.flush()
            n_assess += len(assessments) + len(upcoming)

            roster = [students[e["sid"]] for e in
                      next(r for r in raw_courses if r["code"] == code).get("roster", [])
                      if e.get("state") == "enrolled" and e["sid"] in students]

            for st in roster:
                base, drift, miss_p, _ = ARCHETYPES[archetype[st.sid]]
                for a in assessments:
                    aff = affinity[st.sid].setdefault(a.skill, RNG.uniform(-5.5, 5.5))
                    if RNG.random() < miss_p:
                        # Missing work: sometimes an explicit blank row, sometimes no row.
                        if RNG.random() < 0.5:
                            db.add(Score(assessment_id=a.id, student_id=st.id, points=None))
                            n_scores += 1
                        continue
                    week_index = max(0, (a.due_on - TERM_START).days // 7)
                    pct = (base + drift * (week_index - 2) + course_offset + aff
                           + RNG.gauss(0, 4.5)
                           + (-9.0 if a.skill == gap_skill else 0.0)
                           + (-2.0 if a.kind == "test" else 0.0))
                    pct = max(8.0, min(100.0, pct))
                    late = RNG.random() < 0.12
                    db.add(Score(assessment_id=a.id, student_id=st.id,
                                 points=round(a.max_points * pct / 100.0, 1),
                                 late=late, recorded_on=a.due_on + timedelta(days=2)))
                    n_scores += 1
            db.flush()

        # --- attendance ---------------------------------------------------
        for st in order:
            _, _, _, absent_p = ARCHETYPES[archetype[st.sid]]
            for d in days:
                roll = RNG.random()
                if roll < absent_p:
                    status = "absent" if RNG.random() < 0.75 else "excused"
                elif roll < absent_p + 0.06:
                    status = "tardy"
                else:
                    status = "present"
                db.add(AttendanceDay(student_id=st.id, day=d, status=status))
        db.commit()

        # --- a few support plans already in flight --------------------------
        from app.analytics import build_signals
        sigs = build_signals(db)
        ranked = sorted(sigs.values(), key=lambda s: -s.struggle_index)
        opened = 0
        for sig in ranked:
            if opened >= 4 or not sig.recommendations:
                break
            rec = sig.recommendations[0]
            st = students[sig.sid]
            course = courses.get(rec.course_code) if rec.course_code else None
            db.add(Intervention(
                student_id=st.id, course_id=course.id if course else None,
                kind=rec.kind, title=rec.title, rationale=rec.rationale,
                owner=rec.suggested_owner, status="active",
                opened_on=TODAY - timedelta(days=6 + opened * 2),
                review_on=TODAY + timedelta(days=8)))
            opened += 1
        db.commit()

        bands: dict[str, int] = {}
        for s in sigs.values():
            bands[s.band] = bands.get(s.band, 0) + 1
        means = [c.pct for s in sigs.values() for c in s.courses]
        print(f"students          {len(students)}")
        print(f"stockroom items   {db.query(InventoryItem).count()}"
              f"  ({db.query(InventoryItem).filter(InventoryItem.on_hand <= InventoryItem.reorder_point).count()} below reorder)")
        print(f"courses           {len(courses)}")
        print(f"enrollments       {db.query(Enrollment).count()}")
        print(f"assessments       {n_assess}  ({db.query(Assessment).filter(Assessment.due_on <= TODAY).count()} graded)")
        n_lines, n_txn = seed_finance(db)
        print(f"budget lines      {n_lines}  with {n_txn} transactions")
        print(f"scores            {n_scores}")
        print(f"attendance rows   {db.query(AttendanceDay).count()}  over {len(days)} school days")
        print(f"support plans     {opened} already open")
        print(f"mean course grade {statistics.fmean(means):.1f}%")
        print("bands             " + "  ".join(f"{k}={v}" for k, v in sorted(bands.items())))
    finally:
        db.close()


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--keep", action="store_true", help="leave existing records alone")
    build(**vars(ap.parse_args()))
