"""Baseline schema: every table as it stood when migrations were introduced.

A database created before this (by the old create-at-startup code) already has
these tables. Bring it under migrations with `alembic stamp 0001`, or reseed.

Revision ID: 0001
Revises:
Create Date: 2026-09-13 00:08:21.670834
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('steps_used', sa.Integer(), nullable=False),
    sa.Column('tool_errors', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_subject'), ['subject'], unique=False)

    op.create_table('budget_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('fiscal_year', sa.String(length=8), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_lines'))
    )
    with op.batch_alter_table('budget_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_lines_code'), ['code'], unique=True)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('dept', sa.String(length=60), nullable=False),
    sa.Column('teacher', sa.String(length=120), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('length', sa.String(length=16), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('prerequisite', sa.String(length=200), nullable=False),
    sa.Column('uc_approved', sa.Boolean(), nullable=False),
    sa.Column('extra_period', sa.Boolean(), nullable=False),
    sa.Column('graded', sa.Boolean(), nullable=False),
    sa.Column('catalog_page', sa.Integer(), nullable=True),
    sa.Column('legacy_title', sa.String(length=120), nullable=False),
    sa.Column('signups', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('last_counted', sa.Date(), nullable=True),
    sa.Column('linked_courses', sa.JSON(), nullable=False),
    sa.Column('requisitioned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory'))
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_sku'), ['sku'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('homeroom', sa.String(length=16), nullable=False),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_email', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_sid'), ['sid'], unique=True)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('skill', sa.String(length=80), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('assigned_on', sa.Date(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_assessments_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments'))
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_due_on'), ['due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_skill'), ['skill'], unique=False)

    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_attendance_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('student_id', 'day', name='uq_attendance')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('budget_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_line_id', sa.Integer(), nullable=False),
    sa.Column('to_line_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['from_line_id'], ['budget_lines.id'], name=op.f('fk_budget_transfers_from_line_id_budget_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_line_id'], ['budget_lines.id'], name=op.f('fk_budget_transfers_to_line_id_budget_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_transfers'))
    )
    op.create_table('class_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('focus_strands', sa.JSON(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('review_on', sa.Date(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_class_plans_run_id_agent_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_plans'))
    )
    with op.batch_alter_table('class_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_plans_course_code'), ['course_code'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_enrollments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_enrollments_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollment')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('review_on', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_interventions_course_id_courses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_interventions_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions'))
    )
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interventions_student_id'), ['student_id'], unique=False)

    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('agent', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_proposals_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals'))
    )
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposals_agent'), ['agent'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposals_kind'), ['kind'], unique=False)

    op.create_table('student_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('chars', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('rejected', sa.JSON(), nullable=False),
    sa.Column('notices', sa.JSON(), nullable=False),
    sa.Column('chunks', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('analysed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_documents_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_documents'))
    )
    with op.batch_alter_table('student_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_documents_student_id'), ['student_id'], unique=False)

    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_sid', sa.String(length=16), nullable=False),
    sa.Column('course_code', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('focus_strands', sa.JSON(), nullable=False),
    sa.Column('sessions', sa.JSON(), nullable=False),
    sa.Column('catch_up', sa.JSON(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('review_on', sa.Date(), nullable=True),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_study_plans_run_id_agent_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans'))
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plans_course_code'), ['course_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_student_sid'), ['student_sid'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('posted_on', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('one_time', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['budget_lines.id'], name=op.f('fk_transactions_line_id_budget_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_line_id'), ['line_id'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_scores_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_scores_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('assessment_id', 'student_id', name='uq_score')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_student_id'))
        batch_op.drop_index(batch_op.f('ix_scores_assessment_id'))

    op.drop_table('scores')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_line_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plans_student_sid'))
        batch_op.drop_index(batch_op.f('ix_study_plans_course_code'))

    op.drop_table('study_plans')
    with op.batch_alter_table('student_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_documents_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_documents_sha256'))

    op.drop_table('student_documents')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposals_kind'))
        batch_op.drop_index(batch_op.f('ix_proposals_agent'))

    op.drop_table('proposals')
    with op.batch_alter_table('interventions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interventions_student_id'))

    op.drop_table('interventions')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_course_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('class_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_plans_course_code'))

    op.drop_table('class_plans')
    op.drop_table('budget_transfers')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_day'))

    op.drop_table('attendance')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_skill'))
        batch_op.drop_index(batch_op.f('ix_assessments_due_on'))
        batch_op.drop_index(batch_op.f('ix_assessments_course_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_sid'))

    op.drop_table('students')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_sku'))
        batch_op.drop_index(batch_op.f('ix_inventory_category'))

    op.drop_table('inventory')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    with op.batch_alter_table('budget_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_lines_code'))

    op.drop_table('budget_lines')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_subject'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_parent_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
