"""Account requests from the sign-in screen, pending an administrator's approval.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-13 15:04:58.839875
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('requested_role', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('request_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decided_by', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('decided_by')
        batch_op.drop_column('request_note')
        batch_op.drop_column('requested_role')
        batch_op.drop_column('pending')

    # ### end Alembic commands ###
