"""Keys for re-importing assessments from the SIS, and exempt (excused) scores.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-13 01:03:04.757730
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_source_id'), ['source_id'], unique=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exempt', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('exempt')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_source_id'))
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###
