"""Student history snapshots, staff overrides of a flag, and the reason behind each decision.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-13 00:48:20.106513
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flag_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('computed_band', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('created_by', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=160), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_flag_overrides_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flag_overrides'))
    )
    with op.batch_alter_table('flag_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flag_overrides_student_id'), ['student_id'], unique=False)

    op.create_table('student_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('taken_on', sa.Date(), nullable=False),
    sa.Column('struggle_index', sa.Integer(), nullable=False),
    sa.Column('excel_index', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('absence_rate', sa.Float(), nullable=False),
    sa.Column('open_interventions', sa.Integer(), nullable=False),
    sa.Column('courses', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_snapshots_student_id_students'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_snapshots')),
    sa.UniqueConstraint('student_id', 'taken_on', name='uq_student_snapshot_day')
    )
    with op.batch_alter_table('student_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_snapshots_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_snapshots_taken_on'), ['taken_on'], unique=False)

    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_column('decision_note')

    with op.batch_alter_table('student_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_snapshots_taken_on'))
        batch_op.drop_index(batch_op.f('ix_student_snapshots_student_id'))

    op.drop_table('student_snapshots')
    with op.batch_alter_table('flag_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flag_overrides_student_id'))

    op.drop_table('flag_overrides')
    # ### end Alembic commands ###
